version: '3'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    restart: unless-stopped

  db:
    build:
      context: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  thread:
    build:
      context: ./thread
    depends_on:
      - api
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

  sender:
    build:
      context: ./sender
    depends_on:
      - api
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres_data:
