name: Docker Compose Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo service docker start
          sudo docker-compose build
          sudo docker-compose up -d
        continue-on-error: true

      - name: Show Docker Compose logs
        run: sudo docker-compose logs

      - name: Run SQL Test
        run: |
          sudo docker-compose exec sender sh -c "echo 'INSERT INTO messages (author, content) VALUES ('Admin', 'Hello World!');' | psql -U myforumuser -h db myforumdb"
