name: Docker Compose Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo service docker start
          sudo docker-compose build
          sudo docker-compose up -d
          sudo docker-compose ps
          sudo docker-compose logs -f api
        continue-on-error: true

      - name: Show Docker Compose ps
        run: sudo docker-compose ps

      - name: Wait for services to start
        run: sleep 1

      - name: Show Docker Compose logs
        run: sudo docker-compose logs

      - name: Run fake tests
        run: |
          echo "Running fake tests..."
          
      - name: Tear down Docker Compose
        run: sudo docker-compose down
